5335417 done
WOWMIDEV/WOWMI-prosperity-national-mortgage-payment-calculator pull request #1
Opened 2022-06-16 07:15 UTC by MariPriko

2022-06-17 12:26 UTC, kirillsakun requested changes

2022-06-17 12:26 UTC, kirillsakun commented on app/src/index.html
> +  <div class="container container--footer">
footer__container лучше подойдет

2022-06-17 12:26 UTC, kirillsakun commented on app/src/js/calc.js
> +  if(excludeValue === false) {
`if (!excludeValue)`

2022-06-17 12:26 UTC, kirillsakun commented on app/src/js/calc.js
> +  if(interestRateResult!==0){
(_code style_) пробелы у знака сравнения пропали

2022-06-17 12:26 UTC, kirillsakun commented on app/src/js/calc.js
> +  donutData.forEach(({key, color, data}, index) =>{
(_code style_) пробел перед фигурной скобкой потерялся

2022-06-17 12:26 UTC, kirillsakun commented on app/src/js/calc.js
> +  donutData.forEach(({key, color, data}, index) =>{
color и data не используются вроде, зачем они тут?

2022-06-17 12:26 UTC, kirillsakun commented on app/src/js/render.js
> +      return item
(_code style_): ; в конце строк потерялись. Просто сделай отдельный коммит на фикс ошибок линтера

2022-06-17 12:26 UTC, kirillsakun commented on app/src/scss/styles.scss
> +  padding: 32px;
(_styles_): давайте на rem переходить, отказываемся от px

2022-06-17 12:26 UTC, kirillsakun commented on app/src/scss/styles.scss
> +    margin-right: 5px;
(_styles_): давай в ch или em отступ

2022-06-18 20:08 UTC, MariPriko commented on app/src/js/render.js
> +      return item
Нужно будет в итоге все эти моменты пройти по линтеру

2022-06-23 14:47 UTC, kirillsakun requested changes

2022-06-23 14:47 UTC, kirillsakun commented on app/src/js/render.js
> +  if (resultMonthlyPayment !== null) {
`if (resultMonthlyPayment)`

2022-06-27 10:36 UTC, merged